export { default as AppMain } from './AppMain.vue'
export { default as Navbar } from './Navbar.vue'
export { default as Settings } from './Settings/index.vue'
export { default as License } from './License/index.vue'
export { default as TagsView } from './TagsView/index.vue'
